### ISSUE TITLE
doc mapping type in 7.0 2nd edition example

### ISSUE THREAD

**Issue by cbro1234** [PacktPublishing/Learning-Elastic-Stack-7.0-Second-Edition#4]
This is from 7.0 2nd edition "fixed" version
are mapping types and Doc type not deprecated in 7.0   ?

PUT /amazon_products_with_features
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0,
    "analysis": {
      "analyzer": {}
    }
  },
  "mappings": {
    "doc": {
      "id": {
        "type": "keyword"
      }, .....................................................

results in 
=========================
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Root mapping definition has unsupported parameters:  [feature : {type=keyword}] [price : {scaling_factor=100, type=scaled_float}] [description : {type=text}] [feature_key : {type=keyword}] [id : {type=keyword}] [product_or_feature : {type=join, relations={product=feature}}] [title : {type=text}] [feature_value : {type=keyword}] [manufacturer : {type=text, fields={raw={type=keyword}}}]".......................................

**Comment by cbro1234** [comment]
Changed "doc" to "properties".
seems to have worked

**Comment by ManikandanKurup-Packt** [comment]
Hi @cbro1234,
Thank you for letting us know. Could you let us know which code file had this issue?

**Comment by ManikandanKurup-Packt** [comment]
Thanks for the resolution!
